/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "timer_clock.h"
#include "Muestreo.h"
#include "ADC.h"
#include "DAC.h"
#include "int_EndOfConv.h"
#include "Columnas_aliases.h"
#include "Columnas.h"
#include "Filas_aliases.h"
#include "Filas.h"
#include "int_TeclaOprimida.h"
#include "Recorre_Uno.h"
#include "int_CambioUno.h"
#include "LCD.h"
#include "Entrada_aliases.h"
#include "Entrada.h"
#include "Salida_aliases.h"
#include "Salida.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "DAC_DMA_dma.h"
#include "DAC_VDAC8.h"
#include "DAC_IntClock.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

