# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\nikod\Documents\PSoC Creator\FiltroFIRDigitalProgramable\Proy3_1.cydsn\Proy3_1.cyprj
# Date: Mon, 10 Jun 2019 18:37:43 GMT
#set_units -time ns
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 13.386880856760374 -waveform {0 6.69344042838019} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyMASTER_CLK} -period 13.386880856760374 -waveform {0 6.69344042838019} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {ADC_theACLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 63 125} [list [get_pins {ClockBlock/aclk_glb_0}]]
create_generated_clock -name {timer_clock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 7471 14941} [list [get_pins {ClockBlock/dclk_glb_0}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for C:\Users\nikod\Documents\PSoC Creator\FiltroFIRDigitalProgramable\Proy3_1.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\nikod\Documents\PSoC Creator\FiltroFIRDigitalProgramable\Proy3_1.cydsn\Proy3_1.cyprj
# Date: Mon, 10 Jun 2019 18:37:36 GMT
